### ISSUE TITLE
Fix Ropsten nodes not syncing

### ISSUE THREAD

**Issue by kivutar** [WeTrustPlatform/blockform#36]
The nodes connected to Ropsten network are not syncing.

I suppose we have to download the genesis node and do a `geth --datadir=/datadrive init ropsten.json`, like we did for Rinkeby.. But where to find the json file?

**Comment by hadv** [comment]
I think that not syncing because of lacking peers, it's not the problem of genesis init. When we run node with option --testnet the default genesis was already in the source code, we dont need ropsten.json file thought.

**Comment by kivutar** [comment]
But we use `--networkid 3` here, not `--testnet`.

Maybe that makes a difference, and switching to `--testnet` would be enough to fix it?

**Comment by hadv** [comment]
I run `--testnet` on my local and it worked. But we only have one peer then if the peer shutdown, we cannot sync data from the chain. It'd better to enforce some trusted peers if we know

**Comment by hadv** [comment]
some peers, we can add via https://github.com/ethereum/ropsten#troubleshooting

```
admin.addPeer('enode://94c15d1b9e2fe7ce56e458b9a3b672ef11894ddedd0c6f247e0f1d3487f52b66208fb4aeb8179fce6e3a749ea93ed147c37976d67af557508d199d9594c35f09@192.81.208.223:30303')
admin.addPeer('enode://6332792c4a00e3e4ee0926ed89e0d27ef985424d97b6a45bf0f23e51f0dcb5e66b875777506458aea7af6f9e4ffb69f43f3778ee73c81ed9d34c51c4b16b0b0f@52.232.243.152:30303')
```

**Comment by kivutar** [comment]
What about `static-nodes.json`, have you tried it?

**Comment by hadv** [comment]
> What about `static-nodes.json`, have you tried it?

yes, we can use it instead of `admin.addPeer()` then it's easy for us to do `scp` in the deployment script via ssh

**Comment by kivutar** [comment]
I can set the `static-nodes.json` in the cloud-init script then
