### ISSUE TITLE
Sort nodes on the dashboard

### ISSUE THREAD

**Issue by kivutar** [WeTrustPlatform/blockform#8]
The order is currently changing when we refresh the page if a node is being deleted.

This is confusing.

Do this at the gorm level.

**Comment by hadv** [comment]
It seems already order by `created_at` right?

```
	mux.HandleFunc(pat.Get("/"), func(w http.ResponseWriter, r *http.Request) {
		var nodes []model.Node
		db.Find(&nodes).Order("created_at DESC")
		tmpl.ExecuteTemplate(w, "index.html", nodes)
	})
```

**Comment by kivutar** [comment]
Yeah but for some reasons it's not working. Maybe gorm wants CreatedAt?

**Comment by hadv** [comment]
I think we have to order first then find later to keep the order by. I create PR #33 to fix it. Please check it out @kivutar
